###########################################################################################################
#
#
# Script to install and update SSL certificates for the given domain names. Note 1 certificate is generated for both the domains.
#
#
###################################################################################################################

# To further improve security: https://gist.github.com/cecilemuller/a26737699a7e70a7093d4dc115915de8

---

- name: Update apt
  apt: update_cache=yes


- name: Add certbot PPA repo
  apt_repository:
    repo: ppa:certbot/certbot


- name: Install python-certbot-nginx
  apt: name=python-certbot-nginx state=present


- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ item.servername }}/cert.pem
  register: letsencrypt_cert
  with_items: "{{ apache_vhosts }}"


- name: Generate new certificate if one doesn't exist. This also sets up a cronjob to auto renew the certificate
  shell: "certbot  --{{certbot_create_method}} --noninteractive --redirect --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.servername }}"
  with_items: "{{ letsencrypt_cert.results }}"
  when: item.stat.exists == False


- name: Reload NginX  after cert has been generated.
  service:
    name: "{{ item }}"
    state: reloaded
  with_items: "{{ certbot_create_standalone_stop_services }}"


# Implemented using this https://gist.github.com/cecilemuller/a26737699a7e70a7093d4dc115915de8


- name: Modify nginx conf at /etc/nginx/sites-available/{{project_name}} so that OCSP Stapling is used for cipher verification
  lineinfile:
    path: /etc/nginx/sites-available/{{project_name}}
    insertafter: 'privkey.pem;'
    line: '    ssl_trusted_certificate /etc/letsencrypt/live/www.{{domain_name}}/chain.pem; # added by Arnav'
  notify:
    - Restart NginX and get status


# Make sure these settings help make the site more secure
- name: Edit shared ssl settings to make webserver even more secure
  blockinfile:
    path: /etc/letsencrypt/options-ssl-nginx.conf
    insertafter: "this file\\."
    block: |
      ssl_session_cache shared:le_nginx_SSL:1m;
      ssl_session_timeout 1d;
      ssl_session_tickets off;

      ssl_protocols TLSv1.2;
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
      ssl_ecdh_curve secp384r1;

      ssl_stapling on;
      ssl_stapling_verify on;

      add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload;";
      add_header Referrer-Policy "no-referrer-when-downgrade, strict-origin-when-cross-origin";
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
  notify:
    - Restart NginX and get status

- name: Replace the original content after the new config injection above
  replace:
    path: /etc/letsencrypt/options-ssl-nginx.conf
    after: '# END ANSIBLE MANAGED BLOCK'
    regexp: '^(.+)$'
  notify:
    - Restart NginX and get status
